version: '3.1'
services:

  do-voice-stt-whisper:
    image: dsi-icl/do-voice-stt-whisper:latest
    container_name: do-voice-stt-whisper
    build: stt_whisper_service/
    volumes:
      - "./stt_whisper_service:/usr/src/app"


  # do-voice-stt-service:
  #   image: dsi-icl/do-voice-stt-service:latest
  #   container_name: do-voice-stt-service
  #   build: stt_service/
  #   volumes:
  #     - "./stt_service/config/config.json:/app/config/config.json:ro"

  do-voice-tts_cereproc:
    image: dsi-icl/do-voice-tts-cereproc:latest
    container_name: do-voice-tts-cereproc
    build: tts_cereproc/
    volumes:
      - "./tts_cereproc/config/config.docker.json:/app/config/config.json:ro"
      - "./tts_cereproc/cerevoice/:/app/cerevoice/:ro"
      - "./tts_cereproc/recordings/:/app/recordings/:rw"

  ###  alternative to new cereproc service  ###
  # do-voice-tts-service:
  #   image: dsi-icl/do-voice-tts-service:latest
  #   container_name: do-voice-tts-service
  #   build: tts_service/
  #   volumes:
  #     - "./tts_service/config/config.json:/app/config/config.json:ro"


  do-voice-assistant-service:
    image: dsi-icl/do-voice-assistant-service:latest
    container_name: do-voice-assistant-service
    build:
      context: .
      dockerfile: voice_assistant_service/Dockerfile
    ports:
      - "443:443"
    volumes:
      - "./voice_assistant_service/config/config.docker.json:/app/config/config.json:ro"
      - "./voice_assistant_service/ssl:/app/ssl:ro"


  do-voice-dialog-manager-service:
    image: dsi-icl/do-voice-dialog-manager-service:latest
    container_name: do-voice-dialog-manager-service
    
    volumes:
      - ./dialog_manager_service/models:/app/models:rw
      - ./dialog_manager_service/config/credentials.docker.yml:/app/config/credentials.yml:rw
      - ./dialog_manager_service/config/endpoints.docker.yml:/app/config/endpoints.yml:rw
    build: 
      context: .
      dockerfile: dialog_manager_service/manager_service.Dockerfile


  do-voice-dialog-manager-actions-service:
    image: dsi-icl/do-voice-dialog-manager-actions-service:latest
    container_name: do-voice-dialog-manager-actions-service
    build: 
      context: .
      dockerfile: dialog_manager_service/actions_service.Dockerfile


  do-voice-emotion-recognition-service:
    image: dsi-icl/do-voice-emotion-recognition-service:latest
    container_name: do-voice-emotion-recognition-service
    build: emotion_recognition_service/
    volumes:
      - "./emotion_recognition_service:/usr/src/app"

  do-personality-service:
    image: dsi-icl/do-personality-service:latest
    container_name: do-personality-service
    build: personality_service/
    volumes:
      - "./personality_service:/usr/src/app"


  # do-voice-grammar-correction-service:
  #   image: dsi-icl/do-voice-grammar-correction-service
  #   container_name: do-voice-grammar-correction-service
  #   build: grammar_correction_service/
  #   volumes:
  #     - "./grammar_correction_service:/usr/src/app"

  # do-voice-hotword-service:
  #   image: dsi-icl/do-voice-hotword-service:latest
  #   container_name: do-voice-hotword-service
  #   build: hotword_service/
  #   volumes:
  #     - "./hotword_service/config/config.json:/app/config/config.json:ro"
  #     - "./hotword_service/save:/app/save"
